variables:
  aseToken: C:\ProgramData\HCL\AppScanSource\config\ounceautod.token
  aseHostname: xxxxxxxxxxxxx
  aseAppName: $CI_PROJECT_NAME
  aseApiKeyId: xxxxxxxxxxxxx
  aseApiKeySecret: xxxxxxxxxxxxx
  artifactFolder: $CI_PROJECT_DIR\build\libs 
  artifactName: xxxxxxxxxxxxx.war
  sevSecGw: highIssues
  maxIssuesAllowed: 100

stages:
- scan

scan-job:
  stage: scan
  script:
  - write-host "======== Step 1 - Building artifact ========"
  - gradle clean
  - gradle build

  - Invoke-WebRequest -Uri https://gitlab.prodesp.sp.gov.br/prodesp/devsecops/integracao/templates/appscan/-/raw/master/scripts/appscanase_create_application_ase.ps1 -OutFile appscanase_create_application_ase.ps1
  - .\appscanase_create_application_ase.ps1

  - Invoke-WebRequest -Uri https://gitlab.prodesp.sp.gov.br/prodesp/devsecops/integracao/templates/appscan/-/raw/master/scripts/appscansrc_create_config_scan_file.ps1 -OutFile appscansrc_create_config_scan_file.ps1
  - .\appscansrc_create_config_scan_file.ps1

  - Invoke-WebRequest -Uri https://gitlab.prodesp.sp.gov.br/prodesp/devsecops/integracao/templates/appscan/-/raw/master/scripts/appscansrc_scan.ps1 -OutFile appscansrc_scan.ps1
  - .\appscansrc_scan.ps1

  - Invoke-WebRequest -Uri https://gitlab.prodesp.sp.gov.br/prodesp/devsecops/integracao/templates/appscan/-/raw/master/scripts/appscansrc_publish_assessment_to_enterprise.ps1 -OutFile appscansrc_publish_assessment_to_enterprise.ps1
  - .\appscansrc_publish_assessment_to_enterprise.ps1

  - Invoke-WebRequest -Uri https://gitlab.prodesp.sp.gov.br/prodesp/devsecops/integracao/templates/appscan/-/raw/master/scripts/appscanase_get_xml_report_from_enterprise.ps1 -OutFile appscanase_get_xml_report_from_enterprise.ps1
  - .\appscanase_get_xml_report_from_enterprise.ps1

  - Invoke-WebRequest -Uri https://gitlab.prodesp.sp.gov.br/prodesp/devsecops/integracao/templates/appscan/-/raw/master/scripts/appscanase_convert_ase_sast_xml_to_gitlab_json.ps1 -OutFile appscanase_convert_ase_sast_xml_to_gitlab_json.ps1
  - .\appscanase_convert_ase_sast_xml_to_gitlab_json.ps1

  - Invoke-WebRequest -Uri https://gitlab.prodesp.sp.gov.br/prodesp/devsecops/integracao/templates/appscan/-/raw/master/scripts/appscansrc_check_security_gate.ps1 -OutFile appscansrc_check_security_gate.ps1
  - .\appscansrc_check_security_gate.ps1

  artifacts:
    when: always
    paths:
      - "*.ozasmt"
      - "*.zip"
    reports:
      sast: .\scan_report\gl-sast-report.json
